/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto2.edd.Frontend.Transferencias;

import com.mycompany.proyecto2.edd.Backend.Estructuras.Cola.Cola;
import com.mycompany.proyecto2.edd.Backend.Objetos.Libro;
import com.mycompany.proyecto2.edd.Backend.Util.SistemaBiblioteca;
import com.mycompany.proyecto2.edd.Biblioteca;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author alesso
 */
public class PanelColas extends javax.swing.JPanel {

    private final SistemaBiblioteca sistema;
    private final Map<String, JPanel> filasBibliotecas;

    /**
     * Creates new form PanelColas
     *
     * @param sistema
     */
    public PanelColas(SistemaBiblioteca sistema) {
        initComponents();
        this.sistema = sistema;
        this.filasBibliotecas = new ConcurrentHashMap<>();

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBackground(Color.WHITE);
        actualizarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarPanel() {
        removeAll();

        List<Biblioteca> bibliotecas = sistema.getBibliotecas();

        for (Biblioteca b : bibliotecas) {
            JPanel fila = crearFilaBiblioteca(b);
            filasBibliotecas.put(b.getId(), fila);
            add(fila);
            add(Box.createVerticalStrut(5));
        }

        revalidate();
        repaint();
    }

    private JPanel crearFilaBiblioteca(Biblioteca b) {
        JPanel fila = new JPanel(new BorderLayout());
        fila.setBorder(BorderFactory.createTitledBorder("BIBLIOTECA " + b.getNombre()));
        fila.setBackground(new Color(250, 250, 250));

        JPanel colas = new JPanel(new GridLayout(1, 3, 10, 0));

        colas.add(crearColumna("COLA SALIDA", b.getColaSalida()));
        colas.add(crearColumna("COLA PREPARACION", b.getColaPreparacion()));
        colas.add(crearColumna("COLA INGRESO", b.getColaIngreso()));

        fila.add(colas, BorderLayout.CENTER);
        return fila;
    }

    private JPanel crearColumna(String titulo, Cola cola) {
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.LEFT));
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createTitledBorder(titulo));

        if (cola.estaVacia()) {
            JLabel lblVacio = new JLabel("VACIO");
            lblVacio.setForeground(Color.GRAY);
            panel.add(lblVacio);
        } else {
            for (Libro l : cola.toArray()) {
                JLabel lbl = new JLabel(l.getTitulo());
                lbl.setOpaque(true);
                lbl.setBackground(new Color(70, 130, 180));
                lbl.setForeground(Color.WHITE);
                lbl.setBorder(BorderFactory.createEmptyBorder(3, 6, 3, 6));
                panel.add(lbl);
            }
        }

        return panel;
    }

    public synchronized void actualizarBiblioteca(String idBiblioteca) {
        Biblioteca b = sistema.buscarBibliotecaPorId(idBiblioteca);
        if (b == null) {
            return;
        }

        JPanel fila = filasBibliotecas.get(idBiblioteca);
        if (fila == null) {
            return;
        }

        remove(fila);
        JPanel nuevaFila = crearFilaBiblioteca(b);
        filasBibliotecas.put(idBiblioteca, nuevaFila);
        add(nuevaFila);
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
