/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2.edd.Frontend.Visual;

import com.mycompany.proyecto2.edd.Backend.Util.GeneradorGraphviz;
import com.mycompany.proyecto2.edd.Backend.Util.SistemaBiblioteca;
import com.mycompany.proyecto2.edd.Frontend.Inicio;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author alesso
 */
public class Visualizar extends javax.swing.JFrame {

    private SistemaBiblioteca sistema;
    private GeneradorGraphviz generador;
    private JScrollPane scrollImagen;
    private JLabel lblImagen;

    /**
     * Creates new form Visualizar
     *
     * @param sistema
     */
    public Visualizar(SistemaBiblioteca sistema) {
        this.sistema = sistema;
        this.generador = new GeneradorGraphviz();
        initComponents();
        imagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAvl = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPlus = new javax.swing.JButton();
        btnHash = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VISUALIZAR");
        setResizable(false);

        panelImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("LISTA ENLAZADA");

        btnLista.setText("LISTA");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        jLabel2.setText("ARBOL AVL");

        btnAvl.setText("AVL");
        btnAvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvlActionPerformed(evt);
            }
        });

        btnSalir.setText("REGRESA");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("HASH");

        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        jLabel4.setText("ARBOL B");

        jLabel5.setText("ARBOL B+");

        btnPlus.setText("B+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnHash.setText("HASH");
        btnHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashActionPerformed(evt);
            }
        });

        jLabel7.setText("SELECCIONA EL TIPO DE ESTRUCTURA QUE DESEAS VISUALIZAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 826, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnLista)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnAvl))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnPlus))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHash)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLista)
                    .addComponent(btnAvl)
                    .addComponent(btnB)
                    .addComponent(btnPlus)
                    .addComponent(btnHash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        String path = generador.generarImagenListaEnlazada(this.sistema.getListaPrincipal(), "LISTA");

        if (path != null) {
            File archivo = new File(path);
            if (archivo.exists()) {
                try {
                    Image img = ImageIO.read(archivo);

                    int ancho = lblImagen.getWidth();
                    int alto = lblImagen.getHeight();
                    Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

                    lblImagen.setIcon(new ImageIcon(imgEscalada));
                    lblImagen.setText(null);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                            "EROR AL CARGAR LA IMAGEN",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "NO SE ENCONTRO LA IMAGEN GENERADA: " + path,
                        "Archivo no encontrado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "NO SE PUDO GENERAR LA IMAGEN PARA LA LISTA.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnAvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvlActionPerformed
        String path = generador.generarImagenArbolAVL(this.sistema.getArbolAVL(), "AVL");

        if (path != null) {
            File archivo = new File(path);
            if (archivo.exists()) {
                try {
                    Image img = ImageIO.read(archivo);

                    int ancho = lblImagen.getWidth();
                    int alto = lblImagen.getHeight();
                    Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

                    lblImagen.setIcon(new ImageIcon(imgEscalada));
                    lblImagen.setText(null);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                            "ERROR AL CARGAR LA IMAGEN",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "NO SE ENCONTRO LA IMAGEN GENERADA: " + path,
                        "Archivo no encontrado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "NO SE PUDO GENERAR LA IMAGEN PARA ARBOL AVL.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAvlActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        Inicio inicio = new Inicio(this.sistema);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        String path = generador.generarImagenArbolB(this.sistema.getArbolB(), "B");

        if (path != null) {
            File archivo = new File(path);
            if (archivo.exists()) {
                try {
                    Image img = ImageIO.read(archivo);

                    int ancho = lblImagen.getWidth();
                    int alto = lblImagen.getHeight();
                    Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

                    lblImagen.setIcon(new ImageIcon(imgEscalada));
                    lblImagen.setText(null);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                            "ERROR AL CARGAR IMAGEN",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "NO SE ENCONTRO IMAGEN GENERADA: " + path,
                        "Archivo no encontrado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "NO SE PUDO GENERAR IMAGEN PARA ARBOL B.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        String path = generador.generarImagenArbolBPlus(this.sistema.getArbolBPlus(), "BPLUS");

        if (path != null) {
            File archivo = new File(path);
            if (archivo.exists()) {
                try {
                    Image img = ImageIO.read(archivo);

                    int ancho = lblImagen.getWidth();
                    int alto = lblImagen.getHeight();
                    Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

                    lblImagen.setIcon(new ImageIcon(imgEscalada));
                    lblImagen.setText(null);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                            "ERROR AL CARGAR IMAGEN",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "NO SE ENCONTRO LA IMAGEN GENERADA: " + path,
                        "Archivo no encontrado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "NO SE PUDO GENERAR IMAGEN PARA ARBOL B+.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashActionPerformed
        String path = generador.generarImagenTablaHash(this.sistema.getTablaHash(), "HASH");

        if (path != null) {
            File archivo = new File(path);
            if (archivo.exists()) {
                try {
                    Image img = ImageIO.read(archivo);

                    int ancho = lblImagen.getWidth();
                    int alto = lblImagen.getHeight();
                    Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

                    lblImagen.setIcon(new ImageIcon(imgEscalada));
                    lblImagen.setText(null);
                    lblImagen.revalidate();
                    lblImagen.repaint();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                            "ERROR AL CARGAR IMAGEN",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "NO SE ENCONTRO LA IMAGEN GENERADA: " + path,
                        "Archivo no encontrado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "NO SE PUDO GENERAR LA IMAGEN DE TABLA HASH.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHashActionPerformed

    private void imagen() {
        lblImagen = new JLabel();
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setVerticalAlignment(SwingConstants.CENTER);
        lblImagen.setBackground(Color.WHITE);
        lblImagen.setOpaque(true);

        scrollImagen = new JScrollPane(lblImagen);
        scrollImagen.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollImagen.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollImagen.getVerticalScrollBar().setUnitIncrement(16);

        panelImagen.removeAll();
        panelImagen.setLayout(new BorderLayout());
        panelImagen.add(scrollImagen, BorderLayout.CENTER);
        panelImagen.revalidate();
        panelImagen.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvl;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnHash;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
