/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto2.edd.Frontend.GestionLibros;

import com.mycompany.proyecto2.edd.Backend.Estructuras.ListaEnlazada.ListaEnlazada;
import com.mycompany.proyecto2.edd.Backend.Estructuras.ListaEnlazada.NodoLista;
import com.mycompany.proyecto2.edd.Backend.Objetos.Libro;
import com.mycompany.proyecto2.edd.Backend.Util.SistemaBiblioteca;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alesso
 */
public class BuscarLibro extends javax.swing.JPanel {

    private JTable tablaLibros;
    private DefaultTableModel modeloTablaLibros;
    private List<Libro> libros;
    private SistemaBiblioteca sistema;

    /**
     * Creates new form BuscarLibro
     *
     * @param sistema
     */
    public BuscarLibro(SistemaBiblioteca sistema) {
        this.sistema = sistema;
        initComponents();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JYearChooser();
        date2 = new com.toedter.calendar.JYearChooser();
        panel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(887, 551));
        setMinimumSize(new java.awt.Dimension(887, 551));
        setPreferredSize(new java.awt.Dimension(400, 551));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("BUSCAR:");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        chk1.setText("TITULO");
        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });

        chk2.setText("ISBN");
        chk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk2ActionPerformed(evt);
            }
        });

        chk3.setText("AUTOR");
        chk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk3ActionPerformed(evt);
            }
        });

        chk4.setText("GENERO");
        chk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk4ActionPerformed(evt);
            }
        });

        chk5.setText("RANGO DE AÑOS");
        chk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk5ActionPerformed(evt);
            }
        });

        jLabel2.setText("FIN");

        jLabel3.setText("INICIO");

        date1.setEnabled(false);

        date2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chk1)
                        .addGap(18, 18, 18)
                        .addComponent(chk2)
                        .addGap(18, 18, 18)
                        .addComponent(chk3)
                        .addGap(18, 18, 18)
                        .addComponent(chk4)
                        .addGap(18, 18, 18)
                        .addComponent(chk5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(605, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(224, 224, 224)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chk1)
                        .addComponent(chk2)
                        .addComponent(chk3)
                        .addComponent(chk4)
                        .addComponent(chk5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed
        if (chk1.isSelected()) {
            chk2.setEnabled(false);
            chk3.setEnabled(false);
            chk4.setEnabled(false);
            chk5.setEnabled(false);
        } else {
            chk2.setEnabled(true);
            chk3.setEnabled(true);
            chk4.setEnabled(true);
            chk5.setEnabled(true);
        }
    }//GEN-LAST:event_chk1ActionPerformed

    private void chk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk2ActionPerformed
        if (chk2.isSelected()) {
            chk1.setEnabled(false);
            chk3.setEnabled(false);
            chk4.setEnabled(false);
            chk5.setEnabled(false);
        } else {
            chk1.setEnabled(true);
            chk3.setEnabled(true);
            chk4.setEnabled(true);
            chk5.setEnabled(true);
        }
    }//GEN-LAST:event_chk2ActionPerformed

    private void chk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk3ActionPerformed
        if (chk3.isSelected()) {
            chk1.setEnabled(false);
            chk2.setEnabled(false);
            chk4.setEnabled(false);
            chk5.setEnabled(false);
        } else {
            chk1.setEnabled(true);
            chk2.setEnabled(true);
            chk4.setEnabled(true);
            chk5.setEnabled(true);
        }
    }//GEN-LAST:event_chk3ActionPerformed

    private void chk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk4ActionPerformed
        if (chk4.isSelected()) {
            chk1.setEnabled(false);
            chk3.setEnabled(false);
            chk2.setEnabled(false);
            chk5.setEnabled(false);
        } else {
            chk1.setEnabled(true);
            chk3.setEnabled(true);
            chk2.setEnabled(true);
            chk5.setEnabled(true);
        }
    }//GEN-LAST:event_chk4ActionPerformed

    private void chk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk5ActionPerformed
        if (chk5.isSelected()) {
            chk1.setEnabled(false);
            chk3.setEnabled(false);
            chk4.setEnabled(false);
            chk2.setEnabled(false);
            date1.setEnabled(true);
            date2.setEnabled(true);
        } else {
            chk1.setEnabled(true);
            chk3.setEnabled(true);
            chk4.setEnabled(true);
            chk2.setEnabled(true);
            date1.setEnabled(false);
            date2.setEnabled(false);
        }
    }//GEN-LAST:event_chk5ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarYMostrarResultados();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void inicializarTabla() {
        String[] columnas = {
            "TITULO", "AUTOR", "ISBN", "AÑO", "GENERO",
            "ESTADO", "ACCION"
        };

        modeloTablaLibros = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 6;
            }
        };

        tablaLibros = new JTable(modeloTablaLibros);

        tablaLibros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaLibros.getTableHeader().setReorderingAllowed(false);

        tablaLibros.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaLibros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaLibros.getColumnModel().getColumn(2).setPreferredWidth(150);
        tablaLibros.getColumnModel().getColumn(3).setPreferredWidth(70);
        tablaLibros.getColumnModel().getColumn(4).setPreferredWidth(150);
        tablaLibros.getColumnModel().getColumn(5).setPreferredWidth(150);

        tablaLibros.getColumn("ACCION").setCellRenderer(new ButtonRender());
        tablaLibros.getColumn("ACCION").setCellEditor(new ButtonEditor(new JCheckBox(), modeloTablaLibros, this.sistema));

        JScrollPane scrollPane = new JScrollPane(tablaLibros);
        scrollPane.setPreferredSize(new java.awt.Dimension(800, 300));

        panel.removeAll();
        panel.setLayout(new java.awt.BorderLayout());
        panel.add(scrollPane, java.awt.BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }

    private void buscarYMostrarResultados() {
        modeloTablaLibros.setRowCount(0);

        if (chk1.isSelected()) {
            String titulo = txtBusqueda.getText().trim();
            if (!titulo.isEmpty()) {
                ListaEnlazada libro = sistema.buscarLibrosPorTitulo(titulo);
                agregarListaATabla(libro);
            }

        } else if (chk2.isSelected()) {
            String isbn = txtBusqueda.getText().trim();
            if (!isbn.isEmpty()) {
                ListaEnlazada libro = sistema.buscarLibrosPorISBN(isbn);
                agregarListaATabla(libro);
            }

        } else if (chk3.isSelected()) {
            String autor = txtBusqueda.getText().trim();
            if (!autor.isEmpty()) {
                ListaEnlazada libro = sistema.buscarLibrosPorAutor(autor);
                agregarListaATabla(libro);
            }

        } else if (chk4.isSelected()) {
            String genero = txtBusqueda.getText().trim();
            if (!genero.isEmpty()) {
                ArrayList<Libro> libro = sistema.buscarLibrosPorGenero(genero);
                agregarListaATablaArray(libro);
            } else {
                JOptionPane.showMessageDialog(this, "INGRESE UN GENERO PARA BUSCAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (chk5.isSelected()) {
            try {
                int anioInicio = date1.getYear();
                int anioFin = date2.getYear();

                ArrayList<Libro> libro = sistema.buscarLibrosPorRangoAnios(anioInicio, anioFin);

                agregarListaATablaArray(libro);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                        this,
                        "SELECCIONE FECHAS VALIDAS",
                        "ERROR",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

        panel.revalidate();
        panel.repaint();
    }

    private void agregarLibroATabla(Libro libro) {
        modeloTablaLibros.addRow(new Object[]{
            libro.getTitulo(),
            libro.getAutor(),
            libro.getIsbn(),
            libro.getAnioPublicacion(),
            libro.getGenero(),
            libro.getEstado()
        });
    }

    private void agregarListaATabla(ListaEnlazada lista) {
        if (lista == null) {
            return;
        }
        NodoLista actual = lista.getCabeza();
        while (actual != null) {
            Libro libro = (Libro) actual.getLibro();
            agregarLibroATabla(libro);
            actual = actual.getSiguiente();
        }
    }

    private void agregarListaATablaArray(ArrayList<Libro> libros) {
        modeloTablaLibros.setRowCount(0);
        for (Libro libro : libros) {
            modeloTablaLibros.addRow(new Object[]{
                libro.getTitulo(),
                libro.getAutor(),
                libro.getIsbn(),
                libro.getAnioPublicacion(),
                libro.getGenero(),
                libro.getEstado()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private com.toedter.calendar.JYearChooser date1;
    private com.toedter.calendar.JYearChooser date2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
