/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto2.edd.Frontend.GestionBibliotecas;

import com.mycompany.proyecto2.edd.Backend.Util.SistemaBiblioteca;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author alesso
 */
public class AgregarBiblioteca extends javax.swing.JPanel {

    private SistemaBiblioteca sistema;

    /**
     * Creates new form AgregarBiblioteca
     *
     * @param sistema
     */
    public AgregarBiblioteca(SistemaBiblioteca sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        spIngreso = new javax.swing.JSpinner();
        spTraspaso = new javax.swing.JSpinner();
        spDespacho = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("UBICACION:");

        jLabel3.setText("TIEMPO DE INGRESO (SEG):");

        jLabel4.setText("TIEMPO DE TRASPASO (SEG):");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel5.setText("INTERVALO DE DESPACHO (SEG)");

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(71, 71, 71)
                        .addComponent(btnLimpiar)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUbicacion)
                            .addComponent(txtNombre)
                            .addComponent(spIngreso)
                            .addComponent(spTraspaso)
                            .addComponent(spDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(txtId))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spTraspaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnLimpiar))))
                .addGap(137, 137, 137))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String id = txtId.getText();
        String nombre = txtNombre.getText();
        String ubi = txtUbicacion.getText();
        int ingreso = (Integer) spIngreso.getValue();
        int traspaso = (Integer) spTraspaso.getValue();
        int despacho = (Integer) spDespacho.getValue();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "DEBES DE INGRESAR UN ID",
                    "MENSAJE",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "DEBES DE INGRESAR UN NOMBRE",
                    "MENSAJE",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (ubi.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "DEBES DE INGRESAR UNA UBICACION",
                    "MENSAJE",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (ingreso <= 0) {
            JOptionPane.showMessageDialog(this,
                    "DEBES DE INGRESAR UN NUMERO MAYOR A CERO EN EL INGRESO",
                    "MENSAJE",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (traspaso <= 0) {
            JOptionPane.showMessageDialog(this,
                    "DEBES DE INGRESAR UN NUMERO MAYOR A CERO EN EL TRASPASO",
                    "MENSAJE",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (despacho <= 0) {
            JOptionPane.showMessageDialog(this,
                    "DEBES DE INGRESAR UN NUMERO MAYOR A CERO EN EL DESPACHO",
                    "MENSAJE",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.sistema.agregarBiblioteca(id, nombre, ubi, ingreso, traspaso, despacho)) {
            JOptionPane.showMessageDialog(this,
                    this.sistema.getMensaje(),
                    "MENSAJE",
                    JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this,
                    this.sistema.getMensaje(),
                    "MENSAJE",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void limpiar() {
        this.txtId.setText("");
        this.txtNombre.setText("");
        this.txtUbicacion.setText("");
        this.spTraspaso.setValue(0);
        this.spDespacho.setValue(0);
        this.spIngreso.setValue(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner spDespacho;
    private javax.swing.JSpinner spIngreso;
    private javax.swing.JSpinner spTraspaso;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
